name: CI

on:
  push:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar el código
        uses: actions/checkout@v4

      - name: Instalar uv
        uses: astral-sh/setup-uv@v6

      - name: Instalar dependencias
        run: uv sync --all-extras --dev

      - name: Revisar estilo con ruff
        run: uv run ruff check .

      - name: Ejecutar tests
        run: uv run pytest -v --tb=short